import nltk
from nltk.corpus import stopwords
import pickle

# Download 'punkt' by uncommenting and executing the command below 
#nltk.download('stopwords')


stopset = set(nltk.corpus.stopwords.words('english'))
stopset.add('?')
stopset.add('.')
stopset.add('*')
stopset.add('&')
stopset.add('/')
stopset.add('%')
stopset.add("'")
stopset.add("...")
stopset.add("us")
stopset.add("'s")
stopset.add("n't")
stopset.add(":")
stopset.add("!")
stopset.add("$")
stopset.add("u")
stopset.add(" : ")
stopset.add(" ' ")
stopset.add(";")
stopset.add("' ")
stopset.add(" '")
stopset.add("uhh..")
stopset.add("im")
stopset.add("uh..")
stopset.add("'")
stopset.add("; ")
stopset.add(" ;")
stopset.add(" ' ")
stopset.add("  '")
stopset.add("'  ")
stopset.add("let")
stopset.add("say")
stopset.add("wat")
stopset.add("take")
stopset.add("ain't")
stopset.add("'")
stopset.add("s'")
stopset.add("get")
stopset.add("gets")
stopset.add("thats")
stopset.add("..")
stopset.add("''")
stopset.add("na")
stopset.add("ye")
stopset.add("k")
stopset.add("ur")
stopset.add("ez")
stopset.add("ex")
stopset.add(",")
stopset.add("ok")
stopset.add("(")
stopset.add(")")
stopset.add("got")
stopset.add("gone")
stopset.add("'ll")
stopset.add(" : ")
stopset.add("``")
stopset.add("'ve")
stopset.add('+')
stopset.add('-')
stopset.add('[')
stopset.add(']')
stopset.add('{')
stopset.add('}')
stopset.add('<')
stopset.add('>')
stopset.add('|')
stopset.add('^')
stopset.add('_')
stopset.add('=')
stopset.add('amp')
stopset.add('http')
stopset.add('https')
stopset.add('//')
stopset.add('.com')
stopset.add("'re")
stopset.add("isn't")
stopset.add("doesn't")
stopset.add("'m")


filename = 'stopsetwords'
outfile = open(filename,'wb')
pickle.dump(stopset,outfile)
outfile.close()

print("STOPSET IS UPDATED")